apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: demo-environment
  labels:
    app: demo
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 8888
